// API Service for Insta-Lose
// Uses config.js for API endpoints (generated by scripts/generate-config.sh)

// Fallback for local development - will be overwritten by generate-config.sh
const API_BASE_URL = import.meta.env.VITE_API_URL || "http://localhost:3000";

export const API_ENDPOINTS = {
	createGame: `${API_BASE_URL}/games`,
	joinGame: (gameId) => `${API_BASE_URL}/games/${gameId}/join`,
	getGameState: (gameId) => `${API_BASE_URL}/games/${gameId}`,
	startGame: (gameId) => `${API_BASE_URL}/games/${gameId}/start`,
	takeAction: (gameId) => `${API_BASE_URL}/games/${gameId}/action`,
};

/**
 * Create a new game
 * @param {Object} params - { hostPlayerId }
 * @returns {Promise<{ gameId: string, game: Object }>}
 */
export async function createGame({ hostPlayerId }) {
	const response = await fetch(API_ENDPOINTS.createGame, {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ hostPlayerId }),
	});

	if (!response.ok) {
		const error = await response.json();
		throw new Error(error.error || "Failed to create game");
	}

	return response.json();
}

/**
 * Join an existing game
 * @param {string} gameId - The game code
 * @param {Object} params - { playerId, name, icon, color }
 * @returns {Promise<{ success: boolean, game: Object }>}
 */
export async function joinGame(gameId, { playerId, name, icon, color }) {
	const response = await fetch(API_ENDPOINTS.joinGame(gameId), {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ playerId, name, icon, color }),
	});

	if (!response.ok) {
		const error = await response.json();
		throw new Error(error.error || "Failed to join game");
	}

	return response.json();
}

/**
 * Get current game state (for polling)
 * @param {string} gameId - The game code
 * @param {string|null} playerId - The current player's ID (null for spectator mode)
 * @param {number} lastUpdatedAt - Timestamp of last known update (for 304 optimization)
 * @returns {Promise<Object|null>} - Returns null if not modified (304)
 */
export async function getGameState(gameId, playerId = null, lastUpdatedAt = null) {
	const url = new URL(API_ENDPOINTS.getGameState(gameId));
	if (playerId) url.searchParams.set("playerId", playerId);
	if (lastUpdatedAt) url.searchParams.set("lastUpdatedAt", lastUpdatedAt.toString());

	const response = await fetch(url.toString(), {
		method: "GET",
		headers: { "Content-Type": "application/json" },
	});

	if (response.status === 304) {
		return null; // Not modified
	}

	if (!response.ok) {
		const error = await response.json();
		throw new Error(error.error || "Failed to get game state");
	}

	return response.json();
}

/**
 * Start the game (MVP only)
 * @param {string} gameId - The game code
 * @param {string} playerId - The MVP's player ID
 * @returns {Promise<{ success: boolean, game: Object }>}
 */
export async function startGame(gameId, playerId) {
	const response = await fetch(API_ENDPOINTS.startGame(gameId), {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ playerId }),
	});

	if (!response.ok) {
		const error = await response.json();
		throw new Error(error.error || "Failed to start game");
	}

	return response.json();
}

/**
 * Take a game action (draw card, play card)
 * @param {string} gameId - The game code
 * @param {Object} params - { playerId, actionType, cardId?, targetPlayerId? }
 * @returns {Promise<Object>}
 */
export async function takeAction(gameId, { playerId, actionType, cardId, targetPlayerId }) {
	const response = await fetch(API_ENDPOINTS.takeAction(gameId), {
		method: "POST",
		headers: { "Content-Type": "application/json" },
		body: JSON.stringify({ playerId, actionType, cardId, targetPlayerId }),
	});

	if (!response.ok) {
		const error = await response.json();
		throw new Error(error.error || "Failed to take action");
	}

	return response.json();
}